name: Build and Push multi-architecture Docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker Hub image tag (e.g., latest, v1.0.0)'
        required: true
        default: 'latest'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        # Assumes the action has secrets defined for DockerHub username/token
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          # Build target for both AMD64 and ARM64
          platforms: linux/amd64,linux/arm64
          push: true
          # The image tag name will combine your docker hub username and the provided tag
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sshhelper:${{ github.event.inputs.tag }}
